/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    MenuItem: typeof import('./components/SideMenu/MenuItem.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu/index.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
